<a href="https://colab.research.google.com/github/kavyajeetbora/LB_DSC_SEPT_WKND_20/blob/master/numpy_assignment/kavyajeet/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# Write a Python program to print the NumPy version in your system
np.version.version

'1.18.5'

In [10]:
# Write a Python program to reverse an array (first element becomes last)
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
a[::-1]

[1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [13]:
# Write a Python program to convert a list and tuple into arrays
a = (1,2,3,4,5,6)
b = [1,2,3,4,5,6]
print(type(a),type(b))
print(a)
print(b)

# converting them to arrays
a = np.array(a)
b = np.array(b)
print(type(a),type(b))
print(a)
print(b)

<class 'tuple'> <class 'list'>
(1, 2, 3, 4, 5, 6)
[1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [15]:
# Write a Python program to find common values between two arrays
a = [1,2,3,4,5]
b = [9,4,5,2,7,8,1]
np.intersect1d(a,b)

array([1, 2, 4, 5])

In [24]:
# Write a Python program compare two arrays using numpy
a = np.array([1,2,3,4,5])
b = np.array([9,4,5,2,7,8,1])
np.array_equal(a,b)

False

In [28]:
a = np.array([1,1,1]) == np.array([1,1,1])
a

array([ True,  True,  True])

In [29]:
a.all()

True

**Note:**
(A==B).all() will crash if A and B have different lengths

[Better solution is to use np.array_equal() function for comparison. ](https://stackoverflow.com/a/10580782/6819442) 



In [35]:
# Write a Python program to change the dimension of an array
a = np.zeros(shape=(10,8))
print(a.shape)
b = a.reshape(4,20)
print(b.shape)

(10, 8)
(4, 20)


In [50]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100
a = np.random.randint(low=1,high=100,size=(5,5))
print("Original array:")
print(a)
print("-"*30)

print("Filtered array:")
filtered_array = np.where(np.logical_or(a%3==0, a%5==0), a, 0)
print(filtered_array)
print("-"*30)

print("Summation of elements divisible by 3 or 5")
filtered_array.sum()

Original array:
[[63 79 66 39 69]
 [31 70 21 24 80]
 [68 78 84 92  7]
 [75 91 40 47 46]
 [42 41 26 59 26]]
------------------------------
Filtered array:
[[63  0 66 39 69]
 [ 0 70 21 24 80]
 [ 0 78 84  0  0]
 [75  0 40  0  0]
 [42  0  0  0  0]]
------------------------------
Summation of elements divisible by 3 or 5


751

Solution to this error:

[ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()](https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous)

In [54]:
# Write a Python program to convert a NumPy array into Python list structure
a = np.array([1,2,3,4,5])
list(a)

[1, 2, 3, 4, 5]

In [57]:
# Write a Python program to how to add an extra column to a numpy array
a = np.random.randint(low=1,high=100,size=(5,5))
print(a)
b = np.random.randint(low=1,high=100,size=(5,1))
print(b)
np.hstack((a,b))

[[ 8 98 46 69  9]
 [18 72  6 74 32]
 [49 69 49 16 49]
 [78 62 94 17 63]
 [32 30 67 29 38]]
[[ 8]
 [90]
 [42]
 [19]
 [81]]


array([[ 8, 98, 46, 69,  9,  8],
       [18, 72,  6, 74, 32, 90],
       [49, 69, 49, 16, 49, 42],
       [78, 62, 94, 17, 63, 19],
       [32, 30, 67, 29, 38, 81]])

In [60]:
np.append(a,b,axis=1)  ## using append method

array([[ 8, 98, 46, 69,  9,  8],
       [18, 72,  6, 74, 32, 90],
       [49, 69, 49, 16, 49, 42],
       [78, 62, 94, 17, 63, 19],
       [32, 30, 67, 29, 38, 81]])

In [64]:
# Write a Python program to check whether the numpy array is empty or not
a = np.array([])
print("empty" if a.size == 0 else "not empty")

empty


[To check whether a given array is empty or not](https://stackoverflow.com/a/11295857/6819442)

In [65]:
# Write a Python program to normalize a 3x3 random matrix

a = np.random.randint(low=1,high=100,size=(5,5))
print(a)
def normalize(a):
    '''
    Returns a normalized version of given array
    '''
    mean = np.mean(a)
    std = np.std(a)
    return (a - mean)/std

norm_a = normalize(a)
print(norm_a)

[[38 24 62 22 27]
 [13  1 47 28 44]
 [34 67 18 27 30]
 [52 29 55 19 27]
 [51 86 79 62  5]]
[[ 0.00555445 -0.64246482  1.11644463 -0.735039   -0.50360355]
 [-1.15162281 -1.7070679   0.42213827 -0.45731646  0.28327699]
 [-0.17959391  1.34788008 -0.92018736 -0.50360355 -0.36474227]
 [ 0.65357372 -0.41102936  0.79243499 -0.87390027 -0.50360355]
 [ 0.60728663  2.2273348   1.90332517  1.11644463 -1.52191954]]


In [68]:
# How to ignore all numpy warnings (not recommended)
# np.seterr(all='ignore')

[Set how the numpy errors are handled using np.seterr() function. read more in the documentaion](https://numpy.org/doc/stable/reference/generated/numpy.seterr.html)

In [72]:
# How to swap two rows of an array
a = np.random.randint(low=0,high = 10, size=(5,3))
print(a)

## swap 1st row with 3rd row
x = a.copy()
x[0,:] = a[2,:]
x[2,:] = a[0,:]
print(x)

[[2 6 2]
 [3 5 8]
 [1 4 3]
 [4 4 1]
 [9 0 7]]
[[1 4 3]
 [3 5 8]
 [2 6 2]
 [4 4 1]
 [9 0 7]]


In [82]:
y = a.copy()
print("Original array")
print(a)
print("-"*30)
## swaping rows
y[[0,2],:] = y[[2,0],:]
print("Swaping 1st and 3rd row")
print(y)
print("-"*30)
## swaping columns
z = a.copy()
z[:,[0,2]] = z[:,[2,0]]
print("Swaping 1st and 3rd column")
print(z)
print("-"*30)

Original array
[[1 4 3]
 [3 5 8]
 [2 6 2]
 [4 4 1]
 [9 0 7]]
------------------------------
Swaping 1st and 3rd row
[[2 6 2]
 [3 5 8]
 [1 4 3]
 [4 4 1]
 [9 0 7]]
------------------------------
Swaping 1st and 3rd column
[[3 4 1]
 [8 5 3]
 [2 6 2]
 [1 4 4]
 [7 0 9]]
------------------------------


[Example on how to swap rows](https://stackoverflow.com/a/54069951/6819442)

In [87]:
# Python program to create a random vector of size 10 and sort it
a = np.random.randint(low=0,high=100,size=10)
print("Original array")
print(a)
print("Sorted array")
print(sorted(a))

Original array
[28 23 78 78 63 96 90 58 46  9]
Sorted array
[9, 23, 28, 46, 58, 63, 78, 78, 90, 96]


In [90]:
# Write a Python program to check two random arrays are equal or not
a = np.random.randint(low=0,high=100,size=10)
b = np.random.randint(low=0,high=100,size=10)
print("a:",a)
print("b:",b)
np.array_equal(a,b)

a: [92  0 48 87  2 73 43 50 73 32]
b: [88 82 45 31 24 50 85 12 44 49]


False

In [93]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise
a = a = np.random.randint(low=0,high=100,size=10)
print("a:",a)
print("add:",a+10)
print("subtract:",a+10)
print("multiply:",a*10)
print("divide:",a/10)

a: [23 78 78  9 50 80 33 26  5 71]
add: [33 88 88 19 60 90 43 36 15 81]
subtract: [33 88 88 19 60 90 43 36 15 81]
multiply: [230 780 780  90 500 800 330 260  50 710]
divide: [2.3 7.8 7.8 0.9 5.  8.  3.3 2.6 0.5 7.1]


In [98]:
# Write a Python program to get the dates of yesterday, today and tomorrow

today = np.datetime64("today")
yesterday = today - np.timedelta64(1,"D")
tomorrow = today + np.timedelta64(1,"D")

print("Today:",today)
print("Yesterday:",yesterday)
print("Tomorrow:",tomorrow)

Today: 2020-12-08
Yesterday: 2020-12-07
Tomorrow: 2020-12-09


[How to get dates of today, yesterday and tomorrow](https://www.w3resource.com/python-exercises/numpy/python-numpy-datetime-exercise-2.php)